---
title: "Correlation Plots"
output: html_document
date: "2023-10-06"
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(corrplot)
```

```{r reading data, include=FALSE}
#This loads the data file as the variable "data"
nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/averaged_results.csv')
# Tidying up the data
names(nav_data)[1] <- 'index'
names(nav_data)[2] <- 'Participant'
names(nav_data)[3] <- 'Block_num'
names(nav_data)[4] <- 'Total_Time'
names(nav_data)[5] <- 'Orientation_Time'
names(nav_data)[6] <- 'Navigation_Time'
names(nav_data)[7] <- 'Distance'
names(nav_data)[8] <- 'Speed'
names(nav_data)[9] <- 'Mean_Dwell'
names(nav_data)[10] <- 'Var_X'
names(nav_data)[11] <- 'Var_Y'
names(nav_data)[12] <- 'Var_Z'
names(nav_data)[13] <- 'Teleportations'
nav_data <- nav_data[ -c(1) ]
nav_data$Block_num <- as.factor(nav_data$Block_num)
sapply(nav_data, class)

#This loads the data file as the variable "data"
non_nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA'
non_nav_data <- head(non_nav_data, n=23)
```

```{r organizing data, include=FALSE}
b1 <- subset(nav_data, Block_num == 1)
rownames(b1) <- NULL 
b2 <- subset(nav_data, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(nav_data, Block_num == 3)
rownames(b3) <- NULL 

change <- subset(b3, select = c(Participant))

for (i in 1:nrow(b3)) {
  change$Total_Time[i] <- b3$Total_Time[i] - b1$Total_Time[i]
  change$Orientation_Time[i] <- b3$Orientation_Time[i] - b1$Orientation_Time[i]
  change$Navigation_Time[i] <- b3$Navigation_Time[i] - b1$Navigation_Time[i]
  change$Distance[i] <- b3$Distance[i] - b1$Distance[i]
  change$Speed[i] <- b3$Speed[i] - b1$Speed[i]
  change$Mean_Dwell[i] <- b3$Mean_Dwell[i] - b1$Mean_Dwell[i]
  change$Var_X[i] <- b3$Var_X[i] - b1$Var_X[i]
  change$Var_Y[i] <- b3$Var_Y[i] - b1$Var_Y[i]
  change$Var_Z[i] <- b3$Var_Z[i] - b1$Var_Z[i]
  change$Teleportations[i] <- b3$Teleportations[i] - b1$Teleportations[i]
}

all_blocks <- aggregate(cbind(Total_Time, Orientation_Time, Navigation_Time, 
                              Distance, Speed, Mean_Dwell, Var_X, Var_Y, Var_Z,
                              Teleportations) ~ Participant, 
                        data = nav_data, FUN = mean)

all_blocks$NARA <- non_nav_data$NARA
```

```{r}
remove_outliers <- function(x, na.rm = TRUE) {
  q1 <- quantile(x, 0.25, na.rm = na.rm)
  q3 <- quantile(x, 0.75, na.rm = na.rm)
  iqr <- q3 - q1
  lower_bound <- q1 - 1.5 * iqr
  upper_bound <- q3 + 1.5 * iqr
  x_filtered <- x
  x_filtered[x < lower_bound | x > upper_bound] <- NA
  return(x_filtered)
}

# Remove outliers from the "NARA" variable
all_blocks_wo_outliers <- all_blocks
all_blocks_wo_outliers$Total_Time <- remove_outliers(all_blocks$Total_Time)
all_blocks_wo_outliers$Navigation_Time <- remove_outliers(all_blocks$Navigation_Time)
all_blocks_wo_outliers$Orientation_Time <- remove_outliers(all_blocks$Orientation_Time)
all_blocks_wo_outliers$Distance <- remove_outliers(all_blocks$Distance)
all_blocks_wo_outliers$Speed <- remove_outliers(all_blocks$Speed)
all_blocks_wo_outliers$Var_X <- remove_outliers(all_blocks$Var_X)
all_blocks_wo_outliers$Var_Y <- remove_outliers(all_blocks$Var_Y)
all_blocks_wo_outliers$Var_Z <- remove_outliers(all_blocks$Var_Z)
all_blocks_wo_outliers$Teleportations <- remove_outliers(all_blocks$Teleportations)
```

## Correlations between All-Block All-Target Outcome Measures vs NARA

```{r p_corr_ct}
p_corr_ct <- ggplot(all_blocks_wo_outliers, aes(x=Total_Time, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("Completion Time")+
  ylim(0,100)
p_corr_ct
```

```{r echo=TRUE}
corr_ct <- cor.test(all_blocks_wo_outliers$Total_Time, all_blocks_wo_outliers$NARA)
corr_ct
```

```{r p_corr_ctnav}
p_corr_ctnav <- ggplot(all_blocks_wo_outliers, aes(x=Navigation_Time, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("Navigation Time")+
  ylim(0,100)
p_corr_ctnav
```

```{r echo=TRUE}
corr_ctnav <- cor.test(all_blocks_wo_outliers$Navigation_Time, all_blocks_wo_outliers$NARA)
corr_ctnav
```

```{r p_corr_ctori}
p_corr_ctori <- ggplot(all_blocks_wo_outliers, aes(x=Orientation_Time, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("Orientation_Time")+
  ylim(0,100)
p_corr_ctori
```

```{r echo=TRUE}
corr_ctori <- cor.test(all_blocks_wo_outliers$Orientation_Time, all_blocks_wo_outliers$NARA)
corr_ctori
```

```{r p_corr_dt}
p_corr_dt <- ggplot(all_blocks_wo_outliers, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("Distance")+
  ylim(0,100)
p_corr_dt
```

```{r echo=TRUE}
corr_dt <- cor.test(all_blocks_wo_outliers$Distance, all_blocks_wo_outliers$NARA)
corr_dt
```

```{r p_corr_speed}
p_corr_speed <- ggplot(all_blocks_wo_outliers, aes(x=Speed, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("Speed")+
  ylim(0,100)
p_corr_speed
```

```{r echo=TRUE}
corr_speed <- cor.test(all_blocks_wo_outliers$Speed, all_blocks_wo_outliers$NARA)
corr_speed
```

```{r p_corr_varx}
p_corr_varx <- ggplot(all_blocks_wo_outliers, aes(x=Var_X, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("Var X")+
  ylim(0,100)
p_corr_varx
```

```{r echo=TRUE}
corr_varx <- cor.test(all_blocks_wo_outliers$Var_X, all_blocks_wo_outliers$NARA)
corr_varx
```

```{r p_corr_vary}
p_corr_vary <- ggplot(all_blocks_wo_outliers, aes(x=Var_Y, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("Var Y")+
  ylim(0,100)
p_corr_vary
```

```{r echo=TRUE}
corr_vary <- cor.test(all_blocks_wo_outliers$Var_Y, all_blocks_wo_outliers$NARA)
corr_vary
```


```{r p_corr_varz}
p_corr_varz <- ggplot(all_blocks_wo_outliers, aes(x=Var_Z, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("Var Z")+
  ylim(0,100)
p_corr_varz
```

```{r echo=TRUE}
corr_varz <- cor.test(all_blocks_wo_outliers$Var_Z, all_blocks_wo_outliers$NARA)
corr_varz
```


```{r p_corr_teleport}
p_corr_teleport <- ggplot(all_blocks_wo_outliers, aes(x=Teleportations, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("Teleportations")+
  ylim(0,100)
p_corr_teleport
```

```{r echo=TRUE}
corr_teleport <- cor.test(all_blocks_wo_outliers$Teleportations, all_blocks_wo_outliers$NARA)
corr_teleport
```