---
title: "Correlation Plots"
output: html_document
date: "2023-10-06"
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(corrplot)
```

```{r reading data, include=FALSE}
#This loads the data file as the variable "data"
nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/merged_results.csv')
# Tidying up the data
names(nav_data)[1] <- 'index'
names(nav_data)[2] <- 'Participant'
names(nav_data)[3] <- 'Block_num'
names(nav_data)[4] <- 'Target_Name'
names(nav_data)[5] <- 'Total_Time'
names(nav_data)[6] <- 'Orientation_Time'
names(nav_data)[7] <- 'Navigation_Time'
names(nav_data)[8] <- 'Distance'
names(nav_data)[9] <- 'Speed'
names(nav_data)[10] <- 'Mean_Dwell'
names(nav_data)[11] <- 'Var_X'
names(nav_data)[12] <- 'Var_Y'
names(nav_data)[13] <- 'Var_Z'
names(nav_data)[14] <- 'Teleportations'
nav_data <- nav_data[ -c(1) ]
nav_data$Block_num <- as.factor(nav_data$Block_num)
sapply(nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
nav_data$Target_Name <- factor(nav_data$Target_Name, levels = desired_order)

#This loads the data file as the variable "data"
non_nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA'
non_nav_data <- head(non_nav_data, n=23)
```

```{r organizing data, include=FALSE}
by_block <- nav_data %>%
  group_by(Participant, Block_num) %>%
  summarize(
    Total_Time = mean(Total_Time),
    Orientation_Time = mean(Orientation_Time),
    Navigation_Time = mean(Navigation_Time),
    Distance = mean(Distance),
    Speed = mean(Speed),
    Mean_Dwell = mean(Mean_Dwell),
    Var_X = mean(Var_X),
    Var_Y = mean(Var_Y),
    Var_Z = mean(Var_Z),
    Teleportations = mean(Teleportations)
  )

b1 <- subset(by_block, Block_num == 1)
rownames(b1) <- NULL 
b2 <- subset(by_block, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(by_block, Block_num == 3)
rownames(b3) <- NULL 

change <- subset(b3, select = c(Participant))

for (i in 1:nrow(b3)) {
  change$Total_Time[i] <- b3$Total_Time[i] - b1$Total_Time[i]
  change$Orientation_Time[i] <- b3$Orientation_Time[i] - b1$Orientation_Time[i]
  change$Navigation_Time[i] <- b3$Navigation_Time[i] - b1$Navigation_Time[i]
  change$Distance[i] <- b3$Distance[i] - b1$Distance[i]
  change$Speed[i] <- b3$Speed[i] - b1$Speed[i]
  change$Mean_Dwell[i] <- b3$Mean_Dwell[i] - b1$Mean_Dwell[i]
  change$Var_X[i] <- b3$Var_X[i] - b1$Var_X[i]
  change$Var_Y[i] <- b3$Var_Y[i] - b1$Var_Y[i]
  change$Var_Z[i] <- b3$Var_Z[i] - b1$Var_Z[i]
  change$Teleportations[i] <- b3$Teleportations[i] - b1$Teleportations[i]
}

b1$NARA <- non_nav_data$NARA
b2$NARA <- non_nav_data$NARA
b3$NARA <- non_nav_data$NARA
```


## Correlations for Block 3 Outcomes vs NARA

```{r p_corr_ct b3}
p_corr_ct_b3 <- ggplot(b3, aes(x=Total_Time, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Total Time")+
  ylim(0,100)
p_corr_ct_b3
```

```{r echo=TRUE}
corr_ct_b3 <- cor.test(b3$Total_Time, b3$NARA)
corr_ct_b3
```


```{r p_corr_ctnav b3}
p_corr_ctnav_b3 <- ggplot(b3, aes(x=Navigation_Time, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Navigation Time")+
  ylim(0,100)
p_corr_ctnav_b3
```

```{r echo=TRUE}
corr_ctnav_b3 <- cor.test(b3$Navigation_Time, b3$NARA)
corr_ctnav_b3
```

```{r p_corr_ctori b3}
p_corr_ctori_b3 <- ggplot(b3, aes(x=Orientation_Time, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Orientation Time")+
  ylim(0,100)
p_corr_ctori_b3
```

```{r echo=TRUE}
corr_ctori_b3 <- cor.test(b3$Orientation_Time, b3$NARA)
corr_ctori_b3
```

```{r p_corr_dt b3}
p_corr_dt_b3 <- ggplot(b3, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Distance")+
  ylim(0,100)
p_corr_dt_b3
```

```{r echo=TRUE}
corr_dt_b3 <- cor.test(b3$Distance, b3$NARA)
corr_dt_b3
```

```{r p_corr_speed b3}
p_corr_speed_b3 <- ggplot(b3, aes(x=Speed, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Speed")+
  ylim(0,100)
p_corr_speed_b3
```

```{r echo=TRUE}
corr_speed_b3 <- cor.test(b3$Speed, b3$NARA)
corr_speed_b3
```

```{r p_corr_dwell b3}
p_corr_dwell_b3 <- ggplot(b3, aes(x=Mean_Dwell, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Mean Dwell Time")+
  ylim(0,100)
p_corr_dwell_b3
```

```{r echo=TRUE}
corr_dwell_b3 <- cor.test(b3$Mean_Dwell, b3$NARA)
corr_dwell_b3
```

```{r p_corr_varx b3}
p_corr_varx_b3 <- ggplot(b3, aes(x=Var_X, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Var X")+
  ylim(0,100)
p_corr_varx_b3
```

```{r echo=TRUE}
corr_varx_b3 <- cor.test(b3$Var_X, b3$NARA)
corr_varx_b3
```


```{r p_corr_vary b3}
p_corr_vary_b3 <- ggplot(b3, aes(x=Var_Y, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Var Y")+
  ylim(0,100)
p_corr_vary_b3
```

```{r echo=TRUE}
corr_vary_b3 <- cor.test(b3$Var_Y, b3$NARA)
corr_vary_b3
```


```{r p_corr_varz b3}
p_corr_varz_b3 <- ggplot(b3, aes(x=Var_Z, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Var Z")+
  ylim(0,100)
p_corr_varz_b3
```

```{r echo=TRUE}
corr_varz_b3 <- cor.test(b3$Var_Z, b3$NARA)
corr_varz_b3
```


```{r p_corr_teleport b3}
p_corr_teleport_b3 <- ggplot(b3, aes(x=Teleportations, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  xlab("B3 Teleportations")+
  ylim(0,100)
p_corr_teleport_b3
```

```{r echo=TRUE}
corr_teleport_b3 <- cor.test(b3$Teleportations, b3$NARA)
corr_teleport_b3
```

