---
title: "Outcome Measures Per Target"
output: html_document
date: "2023-05-01"
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(ggplot2)
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library("gridExtra")
```

```{r reading data, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "data"
data <- read.csv('/Users/yasminebassil/Desktop/Data/merged_results.csv')
# Tidying up the data
names(data)[1] <- 'index'
names(data)[2] <- 'Participant'
names(data)[3] <- 'Block_num'
names(data)[4] <- 'Target_Name'
names(data)[5] <- 'Total_Time'
names(data)[6] <- 'Orientation_Time'
names(data)[7] <- 'Navigation_Time'
names(data)[8] <- 'Distance'
names(data)[9] <- 'Speed'
names(data)[10] <- 'Mean_Dwell'
names(data)[11] <- 'Var_X'
names(data)[12] <- 'Var_Y'
names(data)[13] <- 'Var_Z'
names(data)[14] <- 'Teleportations'
data <- data[ -c(1) ]
data$Block_num <- as.factor(data$Block_num)
sapply(data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
data$Target_Name <- factor(data$Target_Name, levels = desired_order)
```

```{r filtering data, include=FALSE}

b1 <- subset(data, Block_num == 1)
rownames(b1) <- NULL 
b2 <- subset(data, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(data, Block_num == 3)
rownames(b3) <- NULL 

change <- subset(b3, select = c(Participant, Target_Name))

for (i in 1:nrow(b3)) {
  change$Total_Time[i] <- b3$Total_Time[i] - b1$Total_Time[i]
  change$Orientation_Time[i] <- b3$Orientation_Time[i] - b1$Orientation_Time[i]
  change$Navigation_Time[i] <- b3$Navigation_Time[i] - b1$Navigation_Time[i]
  change$Distance[i] <- b3$Distance[i] - b1$Distance[i]
  change$Speed[i] <- b3$Speed[i] - b1$Speed[i]
  change$Mean_Dwell[i] <- b3$Mean_Dwell[i] - b1$Mean_Dwell[i]
  change$Var_X[i] <- b3$Var_X[i] - b1$Var_X[i]
  change$Var_Y[i] <- b3$Var_Y[i] - b1$Var_Y[i]
  change$Var_Z[i] <- b3$Var_Z[i] - b1$Var_Z[i]
  change$Teleportations[i] <- b3$Teleportations[i] - b1$Teleportations[i]
}

# Reorder the levels of Target_Name
b1$Target_Name <- factor(b1$Target_Name, levels = desired_order)
b2$Target_Name <- factor(b2$Target_Name, levels = desired_order)
b3$Target_Name <- factor(b3$Target_Name, levels = desired_order)
change$Target_Name <- factor(change$Target_Name, levels = desired_order)

```

```{r ct_b1}
#Data.summary for Total_Time for B1
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Target_Name
p_ct_b1 <- ggplot(b1, aes(x=Target_Name, y=Total_Time, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Total_Time, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Total_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Completion Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,400)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_b1
```

```{r ct_b2}
#Data.summary for Total_Time for B1
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Target_Name
p_ct_b2 <- ggplot(b2, aes(x=Target_Name, y=Total_Time, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Total_Time, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Total_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Completion Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,400)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_b2
```

```{r ct_b3}
#Data.summary for Total_Time for B1
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Target_Name
p_ct_b3 <- ggplot(b3, aes(x=Target_Name, y=Total_Time, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Total_Time, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Total_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Completion Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,400)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_b3
```

```{r ct_change}
#Data.summary for Distance for B3-B1
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Target_Name
p_ct_change <- ggplot(change, aes(x=Target_Name, y=Total_Time, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Total_Time, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Total_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Completion Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-400,200)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_change
```

```{r orict_b1}
#Data.summary for Orientation_Time
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Orientation_Time),
    Orientation_Time = mean(Orientation_Time)
  )
#Orientation Time by Target_Name
p_orict_b1 <- ggplot(b1, aes(x=Target_Name, y=Orientation_Time, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Orientation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Orientation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,25)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_orict_b1
```

```{r orict_b2}
#Data.summary for Orientation_Time
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Orientation_Time),
    Orientation_Time = mean(Orientation_Time)
  )
#Orientation Time by Target_Name
p_orict_b2 <- ggplot(b2, aes(x=Target_Name, y=Orientation_Time, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Orientation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Orientation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,25)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_orict_b2
```

```{r orict_b3}
#Data.summary for Orientation_Time
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Orientation_Time),
    Orientation_Time = mean(Orientation_Time)
  )
#Orientation Time by Target_Name
p_orict_b3 <- ggplot(b3, aes(x=Target_Name, y=Orientation_Time, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Orientation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Orientation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,25)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_orict_b3
```

```{r orict_change}
#Data.summary for Distance for B3-B1
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Orientation_Time),
    Orientation_Time = mean(Orientation_Time)
  )
#Total_time by Target_Name
p_orict_change <- ggplot(change, aes(x=Target_Name, y=Orientation_Time, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Orientation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Orientation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-25,15)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_orict_change
```

```{r navct_b1}
#Data.summary for Navigation_Time
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Navigation_Time),
    Navigation_Time = mean(Navigation_Time)
  )
#Navigation Time by Target_Name
p_navct_b1 <- ggplot(b1, aes(x=Target_Name, y=Navigation_Time, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Navigation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Navigation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,400)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_navct_b1
```

```{r navct_b2}
#Data.summary for Navigation_Time
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Navigation_Time),
    Navigation_Time = mean(Navigation_Time)
  )
#Navigation Time by Target_Name
p_navct_b2 <- ggplot(b2, aes(x=Target_Name, y=Navigation_Time, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Navigation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Navigation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,400)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_navct_b2
```

```{r navct_b3}
#Data.summary for Navigation_Time
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Navigation_Time),
    Navigation_Time = mean(Navigation_Time)
  )
#Navigation Time by Target_Name
p_navct_b3 <- ggplot(b3, aes(x=Target_Name, y=Navigation_Time, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Navigation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Navigation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,400)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_navct_b3
```

```{r navct_change}
#Data.summary for Distance for B3-B1
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Navigation_Time),
    Navigation_Time = mean(Navigation_Time)
  )
#Total_time by Target_Name
p_navct_change <- ggplot(change, aes(x=Target_Name, y=Navigation_Time, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Navigation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Navigation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-400,200)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_navct_change
```

```{r dt_b1}
#Data.summary for Distance
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Distance),
    Distance = mean(Distance)
  )
#Distance by Target_Name
p_dt_b1 <- ggplot(b1, aes(x=Target_Name, y=Distance, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Distance, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Distance, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Distance Traveled (VR Units)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,2500)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dt_b1
```

```{r dt_b2}
#Data.summary for Distance
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Distance),
    Distance = mean(Distance)
  )
#Distance by Target_Name
p_dt_b2 <- ggplot(b2, aes(x=Target_Name, y=Distance, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Distance, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Distance, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Distance Traveled (VR Units)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,2500)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dt_b2
```

```{r dt_b3}
#Data.summary for Distance
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Distance),
    Distance = mean(Distance)
  )
#Distance by Target_Name
p_dt_b3 <- ggplot(b3, aes(x=Target_Name, y=Distance, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Distance, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Distance, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Distance Traveled (VR Units)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,2500)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dt_b3
```

```{r dt_change}
#Data.summary for Distance
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Distance),
    Distance = mean(Distance)
  )
#Distance by Target_Name
p_dt_change <- ggplot(change, aes(x=Target_Name, y=Distance, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Distance, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Distance, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Distance Traveled (VR Units)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-2500,1500)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dt_change
```

```{r speed_b1}
#Data.summary for Speed
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Speed),
    Speed = mean(Speed)
  )
#Speed by Target_Name
p_speed_b1 <- ggplot(b1, aes(x=Target_Name, y=Speed, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Speed, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Speed, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se),
               geom="crossbar", width=0.2, color="#242526")+
  labs(color= "Participant", y="Speed (VR Unit/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,30)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_speed_b1
```

```{r speed_b2}
#Data.summary for Speed
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Speed),
    Speed = mean(Speed)
  )
#Speed by Target_Name
p_speed_b2 <- ggplot(b2, aes(x=Target_Name, y=Speed, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Speed, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Speed, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se),
               geom="crossbar", width=0.2, color="#242526")+
  labs(color= "Participant", y="Speed (VR Unit/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,30)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_speed_b2
```

```{r speed_b3}
#Data.summary for Speed
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Speed),
    Speed = mean(Speed)
  )
#Speed by Target_Name
p_speed_b3 <- ggplot(b3, aes(x=Target_Name, y=Speed, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Speed, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Speed, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se),
               geom="crossbar", width=0.2, color="#242526")+
  labs(color= "Participant", y="Speed (VR Unit/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,30)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_speed_b3
```

```{r speed_change}
#Data.summary for Distance for B3-B1
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Speed),
    Speed = mean(Speed)
  )
#Total_time by Target_Name
p_speed_change <- ggplot(change, aes(x=Target_Name, y=Speed, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Speed, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Speed, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Speed (VR Unit/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-10,20)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_speed_change
```

```{r dwell_b1}
#Data.summary for Mean_Dwell
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Mean_Dwell),
    Mean_Dwell = mean(Mean_Dwell)
  )
#Mean_Dwell by Target_Name
p_dwell_b1 <- ggplot(b1, aes(x=Target_Name, y=Mean_Dwell, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Mean_Dwell, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Dwell Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,4)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dwell_b1
``` 

```{r dwell_b2}
#Data.summary for Mean_Dwell
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Mean_Dwell),
    Mean_Dwell = mean(Mean_Dwell)
  )
#Mean_Dwell by Target_Name
p_dwell_b2 <- ggplot(b2, aes(x=Target_Name, y=Mean_Dwell, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Mean_Dwell, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Dwell Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,4)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dwell_b2
``` 

```{r dwell_b3}
#Data.summary for Mean_Dwell
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Mean_Dwell),
    Mean_Dwell = mean(Mean_Dwell)
  )
#Mean_Dwell by Target_Name
p_dwell_b3 <- ggplot(b3, aes(x=Target_Name, y=Mean_Dwell, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Mean_Dwell, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Dwell Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,4)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dwell_b3
``` 

```{r dwell_change}
#Data.summary for Distance for B3-B1
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Mean_Dwell),
    Mean_Dwell = mean(Mean_Dwell)
  )
#Total_time by Target_Name
p_dwell_change <- ggplot(change, aes(x=Target_Name, y=Mean_Dwell, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Mean_Dwell, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Dwell Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-3,2)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dwell_change
```

```{r varx_b1}
#Data.summary for Var_X
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_X),
    Var_X = mean(Var_X)
  )
#Var_X by Target_Name
p_varx_b1 <- ggplot(b1, aes(x=Target_Name, y=Var_X, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Var_X, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Var_X, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="X Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,25)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varx_b1
```

```{r varx_b2}
#Data.summary for Var_X
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_X),
    Var_X = mean(Var_X)
  )
#Var_X by Target_Name
p_varx_b2 <- ggplot(b2, aes(x=Target_Name, y=Var_X, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Var_X, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Var_X, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="X Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,25)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varx_b2
```

```{r varx_b3}
#Data.summary for Var_X
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_X),
    Var_X = mean(Var_X)
  )
#Var_X by Target_Name
p_varx_b3 <- ggplot(b3, aes(x=Target_Name, y=Var_X, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Var_X, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Var_X, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="X Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,25)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varx_b3
```

```{r varx_change}
#Data.summary for Distance for B3-B1
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_X),
    Var_X = mean(Var_X)
  )
#Total_time by Target_Name
p_varx_change <- ggplot(change, aes(x=Target_Name, y=Var_X, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Var_X, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Var_X, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="X Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-25,25)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varx_change
```

```{r vary_b1}
#Data.summary for Var_Y
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Y),
    Var_Y = mean(Var_Y)
  )
#Var_Y by Target_Name
p_vary_b1 <- ggplot(b1, aes(x=Target_Name, y=Var_Y, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Var_Y, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Var_Y, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Y Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,200)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_vary_b1
```

```{r vary_b2}
#Data.summary for Var_Y
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Y),
    Var_Y = mean(Var_Y)
  )
#Var_Y by Target_Name
p_vary_b2 <- ggplot(b2, aes(x=Target_Name, y=Var_Y, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Var_Y, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Var_Y, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Y Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,200)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_vary_b2
```

```{r vary_b3}
#Data.summary for Var_Y
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Y),
    Var_Y = mean(Var_Y)
  )
#Var_Y by Target_Name
p_vary_b3 <- ggplot(b3, aes(x=Target_Name, y=Var_Y, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Var_Y, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Var_Y, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Y Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,200)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_vary_b3
```

```{r vary_change}
#Data.summary for Distance for B3-B1
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Y),
    Var_Y = mean(Var_Y)
  )
#Total_time by Target_Name
p_vary_change <- ggplot(change, aes(x=Target_Name, y=Var_Y, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Var_Y, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Var_Y, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Y Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-150,150)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_vary_change
```

```{r varz_b1}
#Data.summary for Var_Z
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Z),
    Var_Z = mean(Var_Z)
  )
#Var_Z by Target_Name
p_varz_b1 <- ggplot(b1, aes(x=Target_Name, y=Var_Z, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Var_Z, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Var_Z, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Z Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,15)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varz_b1
```

```{r varz_b2}
#Data.summary for Var_Z
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Z),
    Var_Z = mean(Var_Z)
  )
#Var_Z by Target_Name
p_varz_b2 <- ggplot(b2, aes(x=Target_Name, y=Var_Z, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Var_Z, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Var_Z, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Z Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,15)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varz_b2
```

```{r varz_b3}
#Data.summary for Var_Z
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Z),
    Var_Z = mean(Var_Z)
  )
#Var_Z by Target_Name
p_varz_b3 <- ggplot(b3, aes(x=Target_Name, y=Var_Z, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Var_Z, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Var_Z, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Z Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,15)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varz_b3
```

```{r varz_change}
#Data.summary for Distance for B3-B1
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Z),
    Var_Z = mean(Var_Z)
  )
#Total_time by Target_Name
p_varz_change <- ggplot(change, aes(x=Target_Name, y=Var_Z, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Var_Z, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Var_Z, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Z Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-8,8)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varz_change
```

```{r teleport_b1}
#Data.summary for Teleportations
b1.summary <- b1 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Teleportations),
    Teleportations = mean(Teleportations)
  )
#Teleportations by Target_Name
p_teleport_b1 <- ggplot(b1, aes(x=Target_Name, y=Teleportations, color=Participant))+
  geom_line(b1, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Teleportations, group = Participant),color = 'white', size = 3)+
  geom_point(b1, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant),alpha = .5)+
  geom_line(b1.summary, mapping = aes(x= Target_Name, y = Teleportations, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Teleportations (count)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,350)+
  theme_classic()+
  xlab("Block 1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_teleport_b1
```

```{r teleport_b2}
#Data.summary for Teleportations
b2.summary <- b2 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Teleportations),
    Teleportations = mean(Teleportations)
  )
#Teleportations by Target_Name
p_teleport_b2 <- ggplot(b2, aes(x=Target_Name, y=Teleportations, color=Participant))+
  geom_line(b2, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Teleportations, group = Participant),color = 'white', size = 3)+
  geom_point(b2, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant),alpha = .5)+
  geom_line(b2.summary, mapping = aes(x= Target_Name, y = Teleportations, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Teleportations (count)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,350)+
  theme_classic()+
  xlab("Block 2")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_teleport_b2
```

```{r teleport_b3}
#Data.summary for Teleportations
b3.summary <- b3 %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Teleportations),
    Teleportations = mean(Teleportations)
  )
#Teleportations by Target_Name
p_teleport_b3 <- ggplot(b3, aes(x=Target_Name, y=Teleportations, color=Participant))+
  geom_line(b3, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Teleportations, group = Participant),color = 'white', size = 3)+
  geom_point(b3, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant),alpha = .5)+
  geom_line(b3.summary, mapping = aes(x= Target_Name, y = Teleportations, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Teleportations (count)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,350)+
  theme_classic()+
  xlab("Block 3")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_teleport_b3
```

```{r teleport_change}
#Data.summary for Distance for B3-B1
change.summary <- change %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Teleportations),
    Teleportations = mean(Teleportations)
  )
#Total_time by Target_Name
p_teleport_change <- ggplot(change, aes(x=Target_Name, y=Teleportations, color=Participant))+
  geom_line(change, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant), alpha = .5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(change, mapping = aes(x= Target_Name, y = Teleportations, group = Participant),color = 'white', size = 3)+
  geom_point(change, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant),alpha = .5)+
  geom_line(change.summary, mapping = aes(x= Target_Name, y = Teleportations, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="crossbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Teleportations (count)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(-400,300)+
  theme_classic()+
  xlab("B3-B1")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_teleport_change
```
