---
title: "Correlation Plots"
output: html_document
date: "2023-10-06"
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(corrplot)
```

```{r reading data, include=FALSE}
#This loads the data file as the variable "data"
nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/merged_results.csv')
# Tidying up the data
names(nav_data)[1] <- 'index'
names(nav_data)[2] <- 'Participant'
names(nav_data)[3] <- 'Block_num'
names(nav_data)[4] <- 'Target_Name'
names(nav_data)[5] <- 'Total_Time'
names(nav_data)[6] <- 'Orientation_Time'
names(nav_data)[7] <- 'Navigation_Time'
names(nav_data)[8] <- 'Distance'
names(nav_data)[9] <- 'Speed'
names(nav_data)[10] <- 'Mean_Dwell'
names(nav_data)[11] <- 'Var_X'
names(nav_data)[12] <- 'Var_Y'
names(nav_data)[13] <- 'Var_Z'
names(nav_data)[14] <- 'Teleportations'
nav_data <- nav_data[ -c(1) ]
nav_data$Block_num <- as.factor(nav_data$Block_num)
sapply(nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
nav_data$Target_Name <- factor(nav_data$Target_Name, levels = desired_order)

#This loads the data file as the variable "data"
non_nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA'
non_nav_data <- head(non_nav_data, n=23)
```

```{r organizing data, include=FALSE}
b1 <- subset(nav_data, Block_num == 1)
rownames(b1) <- NULL 
b2 <- subset(nav_data, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(nav_data, Block_num == 3)
rownames(b3) <- NULL 

change <- subset(b3, select = c(Participant, Target_Name))

for (i in 1:nrow(b3)) {
  change$Total_Time[i] <- b3$Total_Time[i] - b1$Total_Time[i]
  change$Orientation_Time[i] <- b3$Orientation_Time[i] - b1$Orientation_Time[i]
  change$Navigation_Time[i] <- b3$Navigation_Time[i] - b1$Navigation_Time[i]
  change$Distance[i] <- b3$Distance[i] - b1$Distance[i]
  change$Speed[i] <- b3$Speed[i] - b1$Speed[i]
  change$Mean_Dwell[i] <- b3$Mean_Dwell[i] - b1$Mean_Dwell[i]
  change$Var_X[i] <- b3$Var_X[i] - b1$Var_X[i]
  change$Var_Y[i] <- b3$Var_Y[i] - b1$Var_Y[i]
  change$Var_Z[i] <- b3$Var_Z[i] - b1$Var_Z[i]
  change$Teleportations[i] <- b3$Teleportations[i] - b1$Teleportations[i]
}

b1$Target_Name <- factor(b1$Target_Name, levels = desired_order)
b2$Target_Name <- factor(b2$Target_Name, levels = desired_order)
b3$Target_Name <- factor(b3$Target_Name, levels = desired_order)
change$Target_Name <- factor(change$Target_Name, levels = desired_order)
```

## Correlations for Distance Traveled Block 1 & NARA Per Target

```{r p_corr_auto b1}
auto <- subset(b1, Target_Name == "Automobile shop")
rownames(auto) <- NULL
auto$NARA <- non_nav_data$NARA

p_corr_auto <- ggplot(auto, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Automobile Shop")+
  xlab("B1 Distance")+
  ylim(0,100)
p_corr_auto
```
```{r echo=TRUE}
corr_auto <- cor.test(auto$Distance, auto$NARA)
corr_auto
```


```{r p_corr_police b1}
police <- subset(b1, Target_Name == "Police station ")
rownames(police) <- NULL
police$NARA <- non_nav_data$NARA

p_corr_police <- ggplot(police, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Police Station")+
  xlab("B1 Distance")+
  ylim(0,100)
p_corr_police
```

```{r echo=TRUE}
corr_police <- cor.test(police$Distance, police$NARA)
corr_police
```

```{r p_corr_fire b1}
fire <- subset(b1, Target_Name == "Fire Station")
rownames(fire) <- NULL
fire$NARA <- non_nav_data$NARA

p_corr_fire <- ggplot(fire, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Fire Station")+
  xlab("B1 Distance")+
  ylim(0,100)
p_corr_fire
```

```{r echo=TRUE}
corr_fire <- cor.test(fire$Distance, fire$NARA)
corr_fire
```

```{r p_corr_bank b1}
bank <- subset(b1, Target_Name == "Bank")
rownames(bank) <- NULL
bank$NARA <- non_nav_data$NARA

p_corr_bank <- ggplot(bank, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Bank")+
  xlab("B1 Distance")+
  ylim(0,100)
p_corr_bank
```

```{r echo=TRUE}
corr_bank <- cor.test(bank$Distance, bank$NARA)
corr_bank
```

```{r p_corr_pawn b1}
pawn <- subset(b1, Target_Name == "Pawn Shop")
rownames(pawn) <- NULL
pawn$NARA <- non_nav_data$NARA

p_corr_pawn <- ggplot(pawn, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Pawn Shop")+
  xlab("B1 Distance")+
  ylim(0,100)
p_corr_pawn
```
```{r echo=TRUE}
corr_pawn <- cor.test(pawn$Distance, pawn$NARA)
corr_pawn
```

```{r p_corr_pizza b1}
pizza <- subset(b1, Target_Name == "Pizzeria")
rownames(pizza) <- NULL
pizza$NARA <- non_nav_data$NARA

p_corr_pizza <- ggplot(pizza, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Pizzeria")+
  xlab("B1 Distance")+
  ylim(0,100)
p_corr_pizza
```

```{r echo=TRUE}
corr_pizza <- cor.test(pizza$Distance, pizza$NARA)
corr_pizza
```

```{r p_corr_quattroki b1}
quattroki <- subset(b1, Target_Name == "Quattroki Restaurant")
rownames(quattroki) <- NULL
quattroki$NARA <- non_nav_data$NARA

p_corr_quattroki <- ggplot(quattroki, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Quattroki Restaurant")+
  xlab("B1 Distance")+
  ylim(0,100)
p_corr_quattroki
```

```{r echo=TRUE}
corr_quattroki <- cor.test(quattroki$Distance, quattroki$NARA)
corr_quattroki
```

```{r p_corr_highschool b1}
highschool <- subset(b1, Target_Name == "High School")
rownames(highschool) <- NULL
highschool$NARA <- non_nav_data$NARA

p_corr_highschool <- ggplot(highschool, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("High School")+
  xlab("B1 Distance")+
  ylim(0,100)
p_corr_highschool
```

```{r echo=TRUE}
corr_highschool <- cor.test(highschool$Distance, highschool$NARA)
corr_highschool
```


## Correlations for Distance Traveled Block 3 - Block 1 & NARA Per Target

```{r p_corr_auto change}
auto <- subset(change, Target_Name == "Automobile shop")
rownames(auto) <- NULL
auto$NARA <- non_nav_data$NARA

p_corr_auto <- ggplot(auto, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Automobile Shop")+
  xlab("B3-B1 Distance")+
  ylim(0,100)
p_corr_auto
```

```{r echo=TRUE}
corr_auto <- cor.test(auto$Distance, auto$NARA)
corr_auto
```

```{r p_corr_police change}
police <- subset(change, Target_Name == "Police station ")
rownames(police) <- NULL
police$NARA <- non_nav_data$NARA

p_corr_police <- ggplot(police, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Police Station")+
  xlab("B3-B1 Distance")+
  ylim(0,100)
p_corr_police
```

```{r echo=TRUE}
corr_police <- cor.test(police$Distance, police$NARA)
corr_police
```



```{r p_corr_fire change}
fire <- subset(change, Target_Name == "Fire Station")
rownames(fire) <- NULL
fire$NARA <- non_nav_data$NARA

p_corr_fire <- ggplot(fire, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Fire Station")+
  xlab("B3-B1 Distance")+
  ylim(0,100)
p_corr_fire
```

```{r echo=TRUE}
corr_fire <- cor.test(fire$Distance, fire$NARA)
corr_fire
```

```{r p_corr_bank change}
bank <- subset(change, Target_Name == "Bank")
rownames(bank) <- NULL
bank$NARA <- non_nav_data$NARA

p_corr_bank <- ggplot(bank, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Bank")+
  xlab("B3-B1 Distance")+
  ylim(0,100)
p_corr_bank
```

```{r echo=TRUE}
corr_bank <- cor.test(bank$Distance, bank$NARA)
corr_bank
```

```{r p_corr_pawn change}
pawn <- subset(change, Target_Name == "Pawn Shop")
rownames(pawn) <- NULL
pawn$NARA <- non_nav_data$NARA

p_corr_pawn <- ggplot(pawn, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Pawn Shop")+
  xlab("B3-B1 Distance")+
  ylim(0,100)
p_corr_pawn
```
```{r echo=TRUE}
corr_pawn <- cor.test(pawn$Distance, pawn$NARA)
corr_pawn
```

```{r p_corr_pizza change}
pizza <- subset(change, Target_Name == "Pizzeria")
rownames(pizza) <- NULL
pizza$NARA <- non_nav_data$NARA

p_corr_pizza <- ggplot(pizza, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Pizzeria")+
  xlab("B3-B1 Distance")+
  ylim(0,100)
p_corr_pizza
```

```{r echo=TRUE}
corr_pizza <- cor.test(pizza$Distance, pizza$NARA)
corr_pizza
```

```{r p_corr_quattroki change}
quattroki <- subset(change, Target_Name == "Quattroki Restaurant")
rownames(quattroki) <- NULL
quattroki$NARA <- non_nav_data$NARA

p_corr_quattroki <- ggplot(quattroki, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("Quattroki Restaurant")+
  xlab("B3-B1 Distance")+
  ylim(0,100)
p_corr_quattroki
```

```{r echo=TRUE}
corr_quattroki <- cor.test(quattroki$Distance, quattroki$NARA)
corr_quattroki
```

```{r p_corr_highschool change}
highschool <- subset(change, Target_Name == "High School")
rownames(highschool) <- NULL
highschool$NARA <- non_nav_data$NARA

p_corr_highschool <- ggplot(highschool, aes(x=Distance, y=NARA)) + 
  geom_point()+
  geom_smooth(method=lm)+
  ggtitle("High School")+
  xlab("B3-B1 Distance")+
  ylim(0,100)
p_corr_highschool
```

```{r echo=TRUE}
corr_highschool <- cor.test(highschool$Distance, highschool$NARA)
corr_highschool
```