---
title: "SfN 2023 Poster Code"
output: html_document
date: "2023-11-08"
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(ggpubr)
library(rstatix)
library(lme4)
#install.packages("lmerTest")
library(lmerTest)
#install.packages('emmeans')
library('emmeans')
#install.packages("svglite")
library(svglite)
```

```{r reading YA data, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "data"
data <- read.csv('/Users/yasminebassil/Desktop/Data/averaged_results.csv')
# Tidying up the data
names(data)[1] <- 'index'
names(data)[2] <- 'Participant'
names(data)[3] <- 'Block_num'
names(data)[4] <- 'Total_Time'
names(data)[5] <- 'Orientation_Time'
names(data)[6] <- 'Navigation_Time'
names(data)[7] <- 'Distance'
names(data)[8] <- 'Speed'
names(data)[9] <- 'Mean_Dwell'
names(data)[10] <- 'Var_X'
names(data)[11] <- 'Var_Y'
names(data)[12] <- 'Var_Z'
names(data)[13] <- 'Teleportations'
data <- data[ -c(1) ]
data$Block_num <- as.factor(data$Block_num)
sapply(data, class)
data
```

```{r reading more YA data, include=FALSE}
#This loads the data file as the variable "data"
nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/merged_results.csv')
# Tidying up the data
names(nav_data)[1] <- 'index'
names(nav_data)[2] <- 'Participant'
names(nav_data)[3] <- 'Block_num'
names(nav_data)[4] <- 'Target_Name'
names(nav_data)[5] <- 'Total_Time'
names(nav_data)[6] <- 'Orientation_Time'
names(nav_data)[7] <- 'Navigation_Time'
names(nav_data)[8] <- 'Distance'
names(nav_data)[9] <- 'Speed'
names(nav_data)[10] <- 'Mean_Dwell'
names(nav_data)[11] <- 'Var_X'
names(nav_data)[12] <- 'Var_Y'
names(nav_data)[13] <- 'Var_Z'
names(nav_data)[14] <- 'Teleportations'
nav_data <- nav_data[ -c(1) ]
nav_data$Block_num <- as.factor(nav_data$Block_num)
sapply(nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
nav_data$Target_Name <- factor(nav_data$Target_Name, levels = desired_order)

#This loads the data file as the variable "data"
non_nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA'
non_nav_data <- head(non_nav_data, n=23)
```

# Figure 1

## Total Time

```{r ct}
#Data.summary for Total_Time
data.summary <- data %>%
  group_by(Block_num) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Block_num
p_ct <- ggplot(data, aes(x=Block_num, y=Total_Time, color=Participant))+
  geom_line(data, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(data, mapping = aes(x= Block_num, y = Total_Time, group = Participant),color = 'white', size = 3)+
  geom_point(data, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(data.summary, mapping = aes(x= Block_num, y = Total_Time, group = 1), size = 1.5, color = '#242526')+
  geom_point(data.summary, mapping = aes(x= Block_num, y = Total_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2,
                color="#242526") +
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c( "Block 1","Block 2","Block 3"))+
  ylim(0,300)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))
p_ct
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig1_ct.svg",
       height = 4, width=5, plot=p_ct)
```



## Orientation Time

```{r orict}
#Data.summary for Orientation_Time
data.summary <- data %>%
  group_by(Block_num) %>%
  summarise(
    se = std.error(Orientation_Time),
    Orientation_Time = mean(Orientation_Time)
  )
#Orientation Time by Block_num
p_orict <- ggplot(data, aes(x=Block_num, y=Orientation_Time, color=Participant))+
  geom_line(data, mapping = aes(x= Block_num, y = Orientation_Time, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(data, mapping = aes(x= Block_num, y = Orientation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(data, mapping = aes(x= Block_num, y = Orientation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(data.summary, mapping = aes(x= Block_num, y = Orientation_Time, group = 1), size = 1.5, color = '#242526')+
  geom_point(data.summary, mapping = aes(x= Block_num, y = Orientation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Orientation Time (s)", x="")+
  scale_x_discrete(labels = c( "Block 1","Block 2","Block 3"))+
  ylim(0,15)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))
p_orict
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig1_orict.svg",
       height = 4, width=5, plot=p_orict)
```

## Navigation Time

```{r navct}
#Data.summary for Navigation_Time
data.summary <- data %>%
  group_by(Block_num) %>%
  summarise(
    se = std.error(Navigation_Time),
    Navigation_Time = mean(Navigation_Time)
  )
#Navigation Time by Block_num
p_navct <- ggplot(data, aes(x=Block_num, y=Navigation_Time, color=Participant))+
  geom_line(data, mapping = aes(x= Block_num, y = Navigation_Time, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(data, mapping = aes(x= Block_num, y = Navigation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(data, mapping = aes(x= Block_num, y = Navigation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(data.summary, mapping = aes(x= Block_num, y = Navigation_Time, group = 1), size = 1.5, color = '#242526')+
  geom_point(data.summary, mapping = aes(x= Block_num, y = Navigation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Navigation Time (s)", x="")+
  scale_x_discrete(labels = c( "Block 1","Block 2","Block 3"))+
  ylim(0,300)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))
p_navct
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig1_navct.svg",
       height = 4, width=5, plot=p_navct)
```

## Distance

```{r dt}
#Data.summary for Distance
data.summary <- data %>%
  group_by(Block_num) %>%
  summarise(
    se = std.error(Distance),
    Distance = mean(Distance)
  )
#Distance by Block_num
p_dt <- ggplot(data, aes(x=Block_num, y=Distance, color=Participant))+
  geom_line(data, mapping = aes(x= Block_num, y = Distance, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(data, mapping = aes(x= Block_num, y = Distance, group = Participant),color = 'white', size = 3)+
  geom_point(data, mapping = aes(x= Block_num, y = Distance, group = Participant, color = Participant),alpha = .5)+
  geom_line(data.summary, mapping = aes(x= Block_num, y = Distance, group = 1), size = 1.5, color = '#242526')+
  geom_point(data.summary, mapping = aes(x= Block_num, y = Distance, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Distance Traveled (VR Units)", x="")+
  scale_x_discrete(labels = c( "Block 1","Block 2","Block 3"))+
  ylim(0,1250)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))
p_dt
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig1_dt.svg",
       height = 4, width=5, plot=p_dt)
```

## Speed

```{r speed}
#Data.summary for Speed
data.summary <- data %>%
  group_by(Block_num) %>%
  summarise(
    se = std.error(Speed),
    Speed = mean(Speed)
  )
#Speed by Block_num
p_speed <- ggplot(data, aes(x=Block_num, y=Speed, color=Participant))+
  geom_line(data, mapping = aes(x= Block_num, y = Speed, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(data, mapping = aes(x= Block_num, y = Speed, group = Participant),color = 'white', size = 3)+
  geom_point(data, mapping = aes(x= Block_num, y = Speed, group = Participant, color = Participant),alpha = .5)+
  geom_line(data.summary, mapping = aes(x= Block_num, y = Speed, group = 1), size = 1.5, color = '#242526')+
  geom_point(data.summary, mapping = aes(x= Block_num, y = Speed, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Speed (VR Unit/s)", x="")+
  scale_x_discrete(labels = c( "Block 1","Block 2","Block 3"))+
  ylim(0,25)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))
p_speed
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig1_speed.svg",
       height = 4, width=5, plot=p_speed)
```

## Dwell Time

```{r dwell}
#Data.summary for Mean_Dwell
data.summary <- data %>%
  group_by(Block_num) %>%
  summarise(
    se = std.error(Mean_Dwell),
    Mean_Dwell = mean(Mean_Dwell)
  )
#Mean_Dwell by Block_num
p_dwell <- ggplot(data, aes(x=Block_num, y=Mean_Dwell, color=Participant))+
  geom_line(data, mapping = aes(x= Block_num, y = Mean_Dwell, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(data, mapping = aes(x= Block_num, y = Mean_Dwell, group = Participant),color = 'white', size = 3)+
  geom_point(data, mapping = aes(x= Block_num, y = Mean_Dwell, group = Participant, color = Participant),alpha = .5)+
  geom_line(data.summary, mapping = aes(x= Block_num, y = Mean_Dwell, group = 1), size = 1.5, color = '#242526')+
  geom_point(data.summary, mapping = aes(x= Block_num, y = Mean_Dwell, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Dwell Time (s)", x="")+
  scale_x_discrete(labels = c( "Block 1","Block 2","Block 3"))+
  ylim(0,3)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))
p_dwell
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig1_dwell.svg",
       height = 4, width=5, plot=p_dwell)
``` 

## Teleportations

```{r teleport}
#Data.summary for Teleportations
data.summary <- data %>%
  group_by(Block_num) %>%
  summarise(
    se = std.error(Teleportations),
    Teleportations = mean(Teleportations)
  )
#Teleportations by Block_num
p_teleport <- ggplot(data, aes(x=Block_num, y=Teleportations, color=Participant))+
  geom_line(data, mapping = aes(x= Block_num, y = Teleportations, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(data, mapping = aes(x= Block_num, y = Teleportations, group = Participant),color = 'white', size = 3)+
  geom_point(data, mapping = aes(x= Block_num, y = Teleportations, group = Participant, color = Participant),alpha = .5)+
  geom_line(data.summary, mapping = aes(x= Block_num, y = Teleportations, group = 1), size = 1.5, color = '#242526')+
  geom_point(data.summary, mapping = aes(x= Block_num, y = Teleportations, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Teleportations to Target (count)", x="")+
  scale_x_discrete(labels = c( "Block 1","Block 2","Block 3"))+
  ylim(0,160)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))
p_teleport
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig1_teleport.svg",
       height = 4, width=5, plot=p_teleport)
```


# Figure 2

## Figure 2 Plots

```{r reading fig 2 data, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "data"
data_ya <- data

age_labels <- read.csv('/Users/yasminebassil/Desktop/age_labels.csv', header=FALSE)
names(age_labels)[1] <- 'Participant'
names(age_labels)[2] <- 'Age'
```

```{r reading older adult data, include=FALSE}
#This data_oa chunk loads and tidies up the data_oa

#This loads the data_oa file as the variable "data_oa"
data_oa <- read.csv('/Users/yasminebassil/Desktop/OA_Data/averaged_results.csv')
# Tidying up data_oa
names(data_oa)[1] <- 'index'
names(data_oa)[2] <- 'Participant'
names(data_oa)[3] <- 'Block_num'
names(data_oa)[4] <- 'Total_Time'
names(data_oa)[5] <- 'Orientation_Time'
names(data_oa)[6] <- 'Navigation_Time'
names(data_oa)[7] <- 'Distance'
names(data_oa)[8] <- 'Speed'
names(data_oa)[9] <- 'Mean_Dwell'
names(data_oa)[10] <- 'Var_X'
names(data_oa)[11] <- 'Var_Y'
names(data_oa)[12] <- 'Var_Z'
names(data_oa)[13] <- 'Teleportations'
data_oa <- data_oa[ -c(1) ]
data_oa$Block_num <- as.factor(data_oa$Block_num)
sapply(data_oa, class)
data_oa

data_oa$Age <- "OA"
data_ya$Age <- "YA"

all_data <- rbind(data_ya, data_oa)
all_data <- all_data[order(all_data$Participant),]

```

### Total Time

```{r ct_all}
#Data.summary for Total_Time for all blocks
all_data.summary <- all_data %>%
  group_by(Block_num, Age) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Block_num

all_data.summaryYA <- subset(all_data.summary, Age == "YA")
all_data.summaryOA <- subset(all_data.summary, Age == "OA")

p_ct_all <- ggplot(all_data, aes(x=Block_num, y=Total_Time, color=Participant))+
  geom_line(all_data, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .1)+
  scale_color_manual(values=c("#822c31", "#c49808"))+
  geom_point(all_data, mapping = aes(x= Block_num, y = Total_Time, group = Age),color = 'white', size = 3)+
  geom_point(all_data, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .5)+
  geom_line(all_data.summaryYA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 1, color = '#c49808')+
  geom_point(all_data.summaryYA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 2, color = '#c49808')+
    geom_line(all_data.summaryOA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 1, color = '#822c31')+
  geom_point(all_data.summaryOA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 2, color = '#822c31')+
  #stat_summary(fun.args = list(mean_se), 
                #geom="errorbar", 
                #width=0.2, 
                #color="#242526") +
  geom_errorbar(all_data.summaryYA, mapping =aes(x=Block_num, ymin=Total_Time-se, ymax=Total_Time+se), width=0.1, colour="#c49808", alpha=0.9, size=1) +
  geom_errorbar(all_data.summaryOA, mapping =aes(x=Block_num, ymin=Total_Time-se, ymax=Total_Time+se), width=0.1, colour="#822c31", alpha=0.9, size=1) +
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,300)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_all
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig2_ct_all.svg", 
       height = 4, width = 5, plot=p_ct_all)
```


```{r ct_all_points_ya}
#Data.summary for Total_Time for all blocks
p_ct_points_ya <- ggplot(data_ya, aes(x=Block_num, y=Total_Time, color=Participant))+
  geom_line(data_ya, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .3)+
  scale_color_manual(values=c("#c49808"))+
  geom_point(data_ya, mapping = aes(x= Block_num, y = Total_Time, group = Age),color = 'white', size = 3)+
  geom_point(data_ya, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .5)+
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,300)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_points_ya
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig2_ct_ya.svg", 
       height = 4, width = 5,  plot=p_ct_points_ya)
```

```{r ct_all_points_oa}
#Data.summary for Total_Time for all blocks
p_ct_points_oa <- ggplot(data_oa, aes(x=Block_num, y=Total_Time, color=Participant))+
  geom_line(data_oa, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .3)+
  scale_color_manual(values=c("#822c31"))+
  geom_point(data_oa, mapping = aes(x= Block_num, y = Total_Time, group = Age),color = 'white', size = 3)+
  geom_point(data_oa, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .5)+
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,300)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_points_oa
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig2_ct_oa.svg", 
       height = 4, width = 5,  plot=p_ct_points_oa)
```

### Distance

```{r dt_all}
#Data.summary for Distance for all blocks
all_data.summary <- all_data %>%
  group_by(Block_num, Age) %>%
  summarise(
    se = std.error(Distance),
    Distance = mean(Distance)
  )
#Total_time by Block_num

all_data.summaryYA <- subset(all_data.summary, Age == "YA")
all_data.summaryOA <- subset(all_data.summary, Age == "OA")

p_dt_all <- ggplot(all_data, aes(x=Block_num, y=Distance, color=Participant))+
  geom_line(all_data, mapping = aes(x= Block_num, y = Distance, group = Participant, color = Age), alpha = .1)+
  scale_color_manual(values=c("#822c31", "#c49808"))+
  geom_point(all_data, mapping = aes(x= Block_num, y = Distance, group = Age),color = 'white', size = 3)+
  geom_point(all_data, mapping = aes(x= Block_num, y = Distance, group = Participant, color = Age), alpha = .5)+
  geom_line(all_data.summaryYA, mapping = aes(x= Block_num, y = Distance, group = Age), size = 1, color = '#c49808')+
  geom_point(all_data.summaryYA, mapping = aes(x= Block_num, y = Distance, group = Age), size = 2, color = '#c49808')+
    geom_line(all_data.summaryOA, mapping = aes(x= Block_num, y = Distance, group = Age), size = 1, color = '#822c31')+
  geom_point(all_data.summaryOA, mapping = aes(x= Block_num, y = Distance, group = Age), size = 2, color = '#822c31')+
  #stat_summary(fun.args = list(mean_se), 
                #geom="errorbar", 
                #width=0.2, 
                #color="#242526") +
  geom_errorbar(all_data.summaryYA, mapping =aes(x=Block_num, ymin=Distance-se, ymax=Distance+se), width=0.1, colour="#c49808", alpha=0.9, size=1) +
  geom_errorbar(all_data.summaryOA, mapping =aes(x=Block_num, ymin=Distance-se, ymax=Distance+se), width=0.1, colour="#822c31", alpha=0.9, size=1) +
  labs(color= "Participant", y="Distance (VR A.U.s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,1250)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dt_all
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig2_dt_all.svg", 
       height = 4, width = 5, plot=p_dt_all)
```


```{r dt_all_points_ya}
#Data.summary for Distance for all blocks
p_dt_points_ya <- ggplot(data_ya, aes(x=Block_num, y=Distance, color=Participant))+
  geom_line(data_ya, mapping = aes(x= Block_num, y = Distance, group = Participant, color = Age), alpha = .3)+
  scale_color_manual(values=c("#c49808"))+
  geom_point(data_ya, mapping = aes(x= Block_num, y = Distance, group = Age),color = 'white', size = 3)+
  geom_point(data_ya, mapping = aes(x= Block_num, y = Distance, group = Participant, color = Age), alpha = .5)+
  labs(color= "Participant", y="Distance (VR A.U.s", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,1250)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dt_points_ya
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig2_dt_ya.svg", 
       height = 4, width = 5,  plot=p_dt_points_ya)
```

```{r dt_all_points_oa}
#Data.summary for Distance for all blocks
p_dt_points_oa <- ggplot(data_oa, aes(x=Block_num, y=Distance, color=Participant))+
  geom_line(data_oa, mapping = aes(x= Block_num, y = Distance, group = Participant, color = Age), alpha = .3)+
  scale_color_manual(values=c("#822c31"))+
  geom_point(data_oa, mapping = aes(x= Block_num, y = Distance, group = Age),color = 'white', size = 3)+
  geom_point(data_oa, mapping = aes(x= Block_num, y = Distance, group = Participant, color = Age), alpha = .5)+
  labs(color= "Participant", y="Distance (VR A.U.s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,1250)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dt_points_oa
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig2_dt_oa.svg", 
       height = 4, width = 5,  plot=p_dt_points_oa)
```

## Figure 2 Stats

### Total Time

```{r}
# Running linear mi
m_ct_ya <- lmer(Total_Time ~ Block_num + (1|Participant), data=data_ya)
m_ct_anova_ya <- anova(m_ct_ya)
m_ct_anova_ya
# omnibus p-values - main effect of this variable
```
```{r}
# Jasmine's code
emm_m_ct_ya <- emmeans(m_ct_ya,~Block_num)
# can look at just Block_num, or just Target_Name; or the interaction with |
# can run the reverse: Target_Name | Block_num for contrasts 
m_ct_ya_contrasts <- pairs(emm_m_ct_ya)
m_ct_ya_contrasts <- as.data.frame(m_ct_ya_contrasts)
```

```{r}
# Running linear mi
m_ct_oa <- lmer(Total_Time ~ Block_num + (1|Participant), data=data_oa)
m_ct_anova_oa <- anova(m_ct_oa)
m_ct_anova_oa
# omnibus p-values - main effect of this variable
```

```{r}
# Jasmine's code
emm_m_ct_oa <- emmeans(m_ct_oa,~Block_num)
# can look at just Block_num, or just Target_Name; or the interaction with |
# can run the reverse: Target_Name | Block_num for contrasts 
m_ct_oa_contrasts <- pairs(emm_m_ct_oa)
m_ct_oa_contrasts <- as.data.frame(m_ct_oa_contrasts)
```

```{r aging effect fig 2 stat}
# Running linear mi
m_ct_aging <- lmer(Total_Time ~ Block_num * Age + (1|Participant), data=all_data)
m_ct_anova_aging <- anova(m_ct_aging)
m_ct_anova_aging
# omnibus p-values - main effect of this variable
```

```{r}
# Jasmine's code
emm_m_ct_aging <- emmeans(m_ct_aging,~Block_num|Age)
# can look at just Block_num, or just Target_Name; or the interaction with |
# can run the reverse: Target_Name | Block_num for contrasts 
m_ct_aging_contrasts <- pairs(emm_m_ct_aging)
m_ct_aging_contrasts <- as.data.frame(m_ct_aging_contrasts)
```

### Distance

```{r}
# Running linear mi
m_dt_ya <- lmer(Distance ~ Block_num + (1|Participant), data=data_ya)
m_dt_anova_ya <- anova(m_dt_ya)
m_dt_anova_ya
# omnibus p-values - main effect of this variable
```

```{r}
# Jasmine's code
emm_m_dt_ya <- emmeans(m_dt_ya,~Block_num)
# can look at just Block_num, or just Target_Name; or the interaction with |
# can run the reverse: Target_Name | Block_num for contrasts 
m_dt_ya_contrasts <- pairs(emm_m_dt_ya)
m_dt_ya_contrasts <- as.data.frame(m_dt_ya_contrasts)
```

```{r}
# Running linear mi
m_dt_oa <- lmer(Distance ~ Block_num + (1|Participant), data=data_oa)
m_dt_anova_oa <- anova(m_dt_oa)
m_dt_anova_oa
# omnibus p-values - main effect of this variable
```

```{r}
# Jasmine's code
emm_m_dt_oa <- emmeans(m_dt_oa,~Block_num)
# can look at just Block_num, or just Target_Name; or the interaction with |
# can run the reverse: Target_Name | Block_num for contrasts 
m_dt_oa_contrasts <- pairs(emm_m_dt_oa)
m_dt_oa_contrasts <- as.data.frame(m_dt_oa_contrasts)
```


# Figure 3

```{r organizing figure 3 data, include=FALSE}

nara <- read.csv('/Users/yasminebassil/Desktop/nara.csv')
names(nara)[1] <- 'Participant'
names(nara)[2] <- 'Age'
names(nara)[3] <- 'Age_Number'
names(nara)[4] <- 'NARA'
nara_ya <- subset(nara, Age == "YA")
nara_oa <- subset(nara, Age == "OA")


data_oa_mean <- aggregate(cbind(Total_Time, Orientation_Time, Navigation_Time, 
                              Distance, Speed, Mean_Dwell, 
                              Teleportations) ~ Participant, 
                        data = data_oa, FUN = mean)

data_oa_mean$NARA <- nara_oa$NARA

data_ya_mean <- aggregate(cbind(Total_Time, Orientation_Time, Navigation_Time, 
                              Distance, Speed, Mean_Dwell, 
                              Teleportations) ~ Participant, 
                        data = data_ya, FUN = mean)

data_ya_mean$NARA <- nara_ya$NARA
```


## Total Time Correlations

```{r p_corr_ct_ya}
p_corr_ct_ya <- ggplot(data_ya_mean, aes(x=Total_Time, y=NARA)) + 
  geom_point(color = "#c49808")+
  geom_smooth(method=lm, color = "black", fill = "#c49808") +
  xlab("Completion Time")+
  xlim(15,150) +
  ylim(0,100) +
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ct_ya
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig3_ct_ya.svg", 
       height = 4, width = 5,  plot=p_corr_ct_ya)
```

```{r echo=TRUE}
corr_ct_ya <- cor.test(data_ya_mean$Total_Time, data_ya_mean$NARA)
corr_ct_ya
```

```{r p_corr_ct_oa}
p_corr_ct_oa <- ggplot(data_oa_mean, aes(x=Total_Time, y=NARA)) + 
  geom_point(color = "#822c31")+
  geom_smooth(method=lm, color = "black", fill = "#822c31") +
  xlab("Completion Time")+
  xlim(15,150) +
  ylim(0,100) +
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ct_oa
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig3_ct_oa.svg", 
       height = 4, width = 5,  plot=p_corr_ct_oa)
```

```{r echo=TRUE}
corr_ct_oa <- cor.test(data_oa_mean$Total_Time, data_oa_mean$NARA)
corr_ct_oa
```
## Distance Correlations

```{r p_corr_dt_ya}
p_corr_dt_ya <- ggplot(data_ya_mean, aes(x=Distance, y=NARA)) + 
  geom_point(color = "#c49808")+
  geom_smooth(method=lm, color = "black", fill = "#c49808") +
  xlab("Distance")+
  xlim(150,820) +
  ylim(0,100) +
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_dt_ya
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig3_dt_ya.svg", 
       height = 4, width = 5,  plot=p_corr_dt_ya)
```

```{r echo=TRUE}
corr_dt_ya <- cor.test(data_ya_mean$Distance, data_ya_mean$NARA)
corr_dt_ya
```

```{r p_corr_dt_oa}
p_corr_dt_oa <- ggplot(data_oa_mean, aes(x=Distance, y=NARA)) + 
  geom_point(color = "#822c31")+
  geom_smooth(method=lm, color = "black", fill = "#822c31") +
  xlab("Distance")+
  xlim(150,820) +
  ylim(0,100) +
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_dt_oa
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig3_dt_oa.svg", 
       height = 4, width = 5,  plot=p_corr_dt_oa)
```

```{r echo=TRUE}
corr_dt_oa <- cor.test(data_oa_mean$Distance, data_oa_mean$NARA)
corr_dt_oa
```

## NARA Scores


```{r}
data_ya_mean$Age <- "YA"
data_oa_mean$Age <- "OA"
data_all_mean <- rbind(data_ya_mean, data_oa_mean)
data_all_mean$Age <- factor(data_all_mean$Age, levels = c("YA", "OA"))
```

```{r}
p_nara <- ggplot(data_all_mean, aes(x=Age, y=NARA, color=Age))+
  geom_point(size=2) + 
  scale_color_manual(values=c("#c49808", "#822c31"))+
  stat_summary(fun.args = list(mult=1), 
                geom="errorbar", width=0.1, color="black", alpha=0.9, size=1) +
  labs(color= "Participant", y="NARA Score", x="Age Group") +
  theme(text = element_text(size = 15),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.position = "none")
p_nara
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Conferences/2023_SfN/fig3_nara.svg", 
       height = 4, width = 2,  plot=p_nara)
```

```{r}
all_nara <- rbind(nara_ya, nara_oa)
nara.aov <- aov(NARA ~ Age, data = all_nara)
summary(nara.aov)
```


# Extra 

```{r ct_all_mean_boxplot}
#Data.summary for Total_Time for all blocks
all_data.summary <- all_data %>%
  group_by(Block_num, Age) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Block_num

all_data.summaryYA <- subset(all_data.summary, Age == "YA")
all_data.summaryOA <- subset(all_data.summary, Age == "OA")

p_ct_mean <- ggplot(all_data, aes(x=Block_num, y=Total_Time, color=Participant))+
  geom_line(all_data.summaryYA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 1, color = '#c49808')+
  geom_point(all_data.summaryYA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 2, color = '#c49808')+
    geom_line(all_data.summaryOA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 1, color = '#822c31')+
  geom_point(all_data.summaryOA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 2, color = '#822c31')+
  geom_crossbar(all_data.summaryYA, mapping =aes(x=Block_num, ymin=Total_Time-se, ymax=Total_Time+se), width=0.1, colour="#c49808", alpha=0.9, size=0.5) +
  geom_crossbar(all_data.summaryOA, mapping =aes(x=Block_num, ymin=Total_Time-se, ymax=Total_Time+se), width=0.1, colour="#822c31", alpha=0.9, size=0.5) +
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,300)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_mean
#ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_ct.svg", plot=p_ct)
```

```{r ct_all_ya_errorbar}
#Data.summary for Total_Time for all blocks
all_data.summary <- all_data %>%
  group_by(Block_num, Age) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Block_num

all_data.summaryYA <- subset(all_data.summary, Age == "YA")
all_data.summaryOA <- subset(all_data.summary, Age == "OA")

p_ct_all_ya <- ggplot(data_ya, aes(x=Block_num, y=Total_Time, color=Participant))+
  geom_line(data_ya, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .2)+
  scale_color_manual(values=c("#c49808"))+
  geom_point(data_ya, mapping = aes(x= Block_num, y = Total_Time, group = Age),color = 'white', size = 3)+
  geom_point(data_ya, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .5)+
    geom_line(all_data.summaryYA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 1, color = '#c49808')+
  geom_point(all_data.summaryYA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 2, color = '#c49808')+
  #stat_summary(fun.args = list(mean_se), 
                #geom="errorbar", 
                #width=0.2, 
                #color="#242526") +
  geom_errorbar(all_data.summaryYA, mapping =aes(x=Block_num, ymin=Total_Time-se, ymax=Total_Time+se), width=0.1, colour="#c49808", alpha=0.9, size=1) +
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,300)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_all_ya
```

```{r ct_all_oa_errorbar}
#Data.summary for Total_Time for all blocks
all_data.summary <- all_data %>%
  group_by(Block_num, Age) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Block_num

all_data.summaryYA <- subset(all_data.summary, Age == "YA")
all_data.summaryOA <- subset(all_data.summary, Age == "OA")

p_ct_all_oa <- ggplot(data_oa, aes(x=Block_num, y=Total_Time, color=Participant))+
  geom_line(data_oa, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .2)+
  scale_color_manual(values=c("#822c31"))+
  geom_point(data_oa, mapping = aes(x= Block_num, y = Total_Time, group = Age),color = 'white', size = 3)+
  geom_point(data_oa, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .5)+
    geom_line(all_data.summaryOA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 1, color = '#822c31')+
  geom_point(all_data.summaryOA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 2, color = '#822c31')+
  #stat_summary(fun.args = list(mean_se), 
                #geom="errorbar", 
                #width=0.2, 
                #color="#242526") +
  geom_errorbar(all_data.summaryOA, mapping =aes(x=Block_num, ymin=Total_Time-se, ymax=Total_Time+se), width=0.1, colour="#822c31", alpha=0.9, size=1) +
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,300)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_all_oa
#ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_ct.svg", plot=p_ct)
```

```{r ct_all_mean_grouped}
#Data.summary for Total_Time for all blocks
all_data.summary <- all_data %>%
  group_by(Block_num, Age) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Block_num

all_data.summaryYA <- subset(all_data.summary, Age == "YA")
all_data.summaryOA <- subset(all_data.summary, Age == "OA")

p_ct_mean <- ggplot(all_data, aes(x=Block_num, y=Total_Time, color=Participant))+
  geom_line(all_data.summaryYA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 1, color = '#c49808')+
  geom_point(all_data.summaryYA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 2, color = '#c49808')+
    geom_line(all_data.summaryOA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 1, color = '#822c31')+
  geom_point(all_data.summaryOA, mapping = aes(x= Block_num, y = Total_Time, group = Age), size = 2, color = '#822c31')+
  geom_errorbar(all_data.summaryYA, mapping =aes(x=Block_num, ymin=Total_Time-se, ymax=Total_Time+se), width=0.1, colour="#c49808", alpha=0.9, size=1) +
  geom_errorbar(all_data.summaryOA, mapping =aes(x=Block_num, ymin=Total_Time-se, ymax=Total_Time+se), width=0.1, colour="#822c31", alpha=0.9, size=1) +
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,300)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_mean
#ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_ct.svg", plot=p_ct)
```

```{r ct_all_points_only}
#Data.summary for Total_Time for all blocks
all_data.summary <- all_data %>%
  group_by(Block_num, Age) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Block_num

all_data.summaryYA <- subset(all_data.summary, Age == "YA")
all_data.summaryOA <- subset(all_data.summary, Age == "OA")

p_ct_points <- ggplot(all_data, aes(x=Block_num, y=Total_Time, color=Participant))+
  geom_line(all_data, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .3)+
  scale_color_manual(values=c("#822c31", "#c49808"))+
  geom_point(all_data, mapping = aes(x= Block_num, y = Total_Time, group = Age),color = 'white', size = 3)+
  geom_point(all_data, mapping = aes(x= Block_num, y = Total_Time, group = Participant, color = Age), alpha = .5)+
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c("B1", "B2", "B3"))+
  ylim(0,300)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct_points
#ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_ct.svg", plot=p_ct)
```
