---
title: "Figure 4 Code"
output: html_document
date: "2023-11-01"
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(ggpubr)
library(rstatix)
library(lme4)
#install.packages("lmerTest")
library(lmerTest)
#install.packages('emmeans')
library('emmeans')
```

```{r reading data, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "data"
data <- read.csv('/Users/yasminebassil/Desktop/Data/averaged_results.csv')
# Tidying up the data
names(data)[1] <- 'index'
names(data)[2] <- 'Participant'
names(data)[3] <- 'Block_num'
names(data)[4] <- 'Total_Time'
names(data)[5] <- 'Orientation_Time'
names(data)[6] <- 'Navigation_Time'
names(data)[7] <- 'Distance'
names(data)[8] <- 'Speed'
names(data)[9] <- 'Mean_Dwell'
names(data)[10] <- 'Var_X'
names(data)[11] <- 'Var_Y'
names(data)[12] <- 'Var_Z'
names(data)[13] <- 'Teleportations'
data <- data[ -c(1) ]
data$Block_num <- as.factor(data$Block_num)
sapply(data, class)
data
```

```{r reading more data, include=FALSE}
#This loads the data file as the variable "data"
nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/merged_results.csv')
# Tidying up the data
names(nav_data)[1] <- 'index'
names(nav_data)[2] <- 'Participant'
names(nav_data)[3] <- 'Block_num'
names(nav_data)[4] <- 'Target_Name'
names(nav_data)[5] <- 'Total_Time'
names(nav_data)[6] <- 'Orientation_Time'
names(nav_data)[7] <- 'Navigation_Time'
names(nav_data)[8] <- 'Distance'
names(nav_data)[9] <- 'Speed'
names(nav_data)[10] <- 'Mean_Dwell'
names(nav_data)[11] <- 'Var_X'
names(nav_data)[12] <- 'Var_Y'
names(nav_data)[13] <- 'Var_Z'
names(nav_data)[14] <- 'Teleportations'
nav_data <- nav_data[ -c(1) ]
nav_data$Block_num <- as.factor(nav_data$Block_num)
sapply(nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
nav_data$Target_Name <- factor(nav_data$Target_Name, levels = desired_order)

#This loads the data file as the variable "data"
non_nav_data <- read.csv('/Users/yasminebassil/Desktop/Data/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA'
non_nav_data <- head(non_nav_data, n=23)
```


```{r organizing data, include=FALSE}
b1 <- subset(nav_data, Block_num == 1)
rownames(b1) <- NULL 
b2 <- subset(nav_data, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(nav_data, Block_num == 3)
rownames(b3) <- NULL 

change <- subset(b3, select = c(Participant, Target_Name))

for (i in 1:nrow(b3)) {
  change$Total_Time[i] <- b3$Total_Time[i] - b1$Total_Time[i]
  change$Orientation_Time[i] <- b3$Orientation_Time[i] - b1$Orientation_Time[i]
  change$Navigation_Time[i] <- b3$Navigation_Time[i] - b1$Navigation_Time[i]
  change$Distance[i] <- b3$Distance[i] - b1$Distance[i]
  change$Speed[i] <- b3$Speed[i] - b1$Speed[i]
  change$Mean_Dwell[i] <- b3$Mean_Dwell[i] - b1$Mean_Dwell[i]
  change$Var_X[i] <- b3$Var_X[i] - b1$Var_X[i]
  change$Var_Y[i] <- b3$Var_Y[i] - b1$Var_Y[i]
  change$Var_Z[i] <- b3$Var_Z[i] - b1$Var_Z[i]
  change$Teleportations[i] <- b3$Teleportations[i] - b1$Teleportations[i]
}

b1$Target_Name <- factor(b1$Target_Name, levels = desired_order)
b2$Target_Name <- factor(b2$Target_Name, levels = desired_order)
b3$Target_Name <- factor(b3$Target_Name, levels = desired_order)
change$Target_Name <- factor(change$Target_Name, levels = desired_order)
```

```{r}
target_data <- nav_data %>%
  group_by(Participant, Target_Name) %>%
  summarize(Total_Time = mean(Total_Time),
            Orientation_Time = mean(Orientation_Time),
            Navigation_Time = mean(Navigation_Time),
            Distance = mean(Distance),
            Speed = mean(Speed),
            Mean_Dwell = mean(Mean_Dwell),
            Teleportations = mean(Teleportations),
            Var_X = mean(Var_X),
            Var_Y = mean(Var_Y),
            Var_Z = mean(Var_Z))
```

```{r}
all_target_data <- nav_data %>%
  group_by(Target_Name) %>%
  summarize(Total_Time = mean(Total_Time),
            Orientation_Time = mean(Orientation_Time),
            Navigation_Time = mean(Navigation_Time),
            Distance = mean(Distance),
            Speed = mean(Speed),
            Mean_Dwell = mean(Mean_Dwell),
            Teleportations = mean(Teleportations),
            Var_X = mean(Var_X),
            Var_Y = mean(Var_Y),
            Var_Z = mean(Var_Z))
```

# Total Time

```{r ct}
#Data.summary for Total_Time for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
#Total_time by Target_Name
p_ct <- ggplot(target_data, aes(x=Target_Name, y=Total_Time, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Total_Time, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Total_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Total_Time, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Total_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Time to Target (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,200)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_ct
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_ct.svg", plot=p_ct)
```

# Orientation Time

```{r orict}
#Data.summary for Orientation_Time for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Orientation_Time),
    Orientation_Time = mean(Orientation_Time)
  )
#Total_time by Target_Name
p_orict <- ggplot(target_data, aes(x=Target_Name, y=Orientation_Time, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Orientation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Orientation_Time, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Orientation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Orientation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,15)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_orict
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_orict.svg", plot=p_ct)
```

# Navigation Time

```{r navct}
#Data.summary for Navigation_Time for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Navigation_Time),
    Navigation_Time = mean(Navigation_Time)
  )
#Total_time by Target_Name
p_navct <- ggplot(target_data, aes(x=Target_Name, y=Navigation_Time, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Navigation_Time, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Navigation_Time, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Navigation_Time, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Navigation Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,200)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_navct
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_navct.svg", plot=p_navct)
```

# Distance

```{r dt}
#Data.summary for Distance Traveled for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Distance),
    Distance = mean(Distance)
  )
#Total_time by Target_Name
p_dt <- ggplot(target_data, aes(x=Target_Name, y=Distance, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Distance, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Distance, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Distance, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Distance, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Distance Traveled (VR Units)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,1000)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dt
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_dt.svg", plot=p_dt)
```

# Speed

```{r speed}
#Data.summary for Speed for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Speed),
    Speed = mean(Speed)
  )
#Total_time by Target_Name
p_speed <- ggplot(target_data, aes(x=Target_Name, y=Speed, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Speed, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Speed, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Speed, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Speed, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Speed (VR Unit/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,25)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_speed
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_speed.svg", plot=p_speed)
```

# Dwell Time

```{r dwell}
#Data.summary for Mean_Dwell for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Mean_Dwell),
    Mean_Dwell = mean(Mean_Dwell)
  )
#Total_time by Target_Name
p_dwell <- ggplot(target_data, aes(x=Target_Name, y=Mean_Dwell, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Mean_Dwell, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Mean_Dwell, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Mean_Dwell, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Dwell Time (s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,3)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_dwell
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_dwell.svg", plot=p_dwell, width=6)
```

# Teleportations

```{r teleport}
#Data.summary for Teleportations for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Teleportations),
    Teleportations = mean(Teleportations)
  )
#Total_time by Target_Name
p_teleport <- ggplot(target_data, aes(x=Target_Name, y=Teleportations, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Teleportations, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Teleportations, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Teleportations, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Teleportations, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Mean Teleportations to Target (count)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,160)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_teleport
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_teleport.svg", plot=p_teleport)
```

# Variance X

```{r varx}
#Data.summary for Var_X for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_X),
    Var_X = mean(Var_X)
  )
#Total_time by Target_Name
p_varx <- ggplot(target_data, aes(x=Target_Name, y=Var_X, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Var_X, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Var_X, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Var_X, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Var_X, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="X Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,20)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varx
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_varx.svg", plot=p_varx)
```

# Variance Y

```{r vary}
#Data.summary for Var_Y for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Y),
    Var_Y = mean(Var_Y)
  )
#Total_time by Target_Name
p_vary <- ggplot(target_data, aes(x=Target_Name, y=Var_Y, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Var_Y, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Var_Y, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Var_Y, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Var_Y, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Y Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,190)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_vary
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_vary.svg", plot=p_vary)
```
 
# Variance Z

```{r varz}
#Data.summary for Var_Z for all blocks
target_data.summary <- target_data %>%
  group_by(Target_Name) %>%
  summarise(
    se = std.error(Var_Z),
    Var_Z = mean(Var_Z)
  )
#Total_time by Target_Name
p_varz <- ggplot(target_data, aes(x=Target_Name, y=Var_Z, color=Participant))+
  geom_line(target_data, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant), alpha = .3)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Var_Z, group = Participant),color = 'white', size = 3)+
  geom_point(target_data, mapping = aes(x= Target_Name, y = Var_Z, group = Participant, color = Participant),alpha = .5)+
  geom_line(target_data.summary, mapping = aes(x= Target_Name, y = Var_Z, group = 1), size = 1.5, color = '#242526')+
  geom_point(target_data.summary, mapping = aes(x= Target_Name, y = Var_Z, group = 1), size = 1.5, color = '#242526')+
  stat_summary(fun.args = list(mean_se), 
                geom="errorbar", 
                width=0.2, 
                color="#242526") +
  labs(color= "Participant", y="Z Euler Angle Variation (degrees/s)", x="")+
  scale_x_discrete(labels = c("T1","T2","T3", "T4", "T5", "T6", "T7", "T8"))+
  ylim(0,10)+
  theme_classic()+
  xlab("All Blocks")+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=16))+
  theme(axis.text.y = element_text(size=16))+
  theme(axis.title.y = element_text(size=16))+
  theme(axis.title.x = element_text(size=16))
p_varz
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig4_varz.svg", plot=p_varz)
```