---
title: "Correlation Plots: Mean Across Blocks"
output: html_document
date: "2025-06-04"
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(corrplot)
```

```{r reading data, include=FALSE}
#This loads the data file as the variable "data"
nav_data <- read.csv('/Users/yasminebassil/Desktop/everything/YA_Data/averaged_results.csv')
# Tidying up the data
names(nav_data)[1] <- 'index'
names(nav_data)[2] <- 'Participant'
names(nav_data)[3] <- 'Block_num'
names(nav_data)[4] <- 'Total_Time'
names(nav_data)[5] <- 'Orientation_Time'
names(nav_data)[6] <- 'Navigation_Time'
names(nav_data)[7] <- 'Distance'
names(nav_data)[8] <- 'Speed'
names(nav_data)[9] <- 'Mean_Dwell'
names(nav_data)[10] <- 'Teleportations'
nav_data <- nav_data[ -c(1) ]
nav_data$Block_num <- as.factor(nav_data$Block_num)
sapply(nav_data, class)

#This loads the data file as the variable "data"
non_nav_data <- read.csv('/Users/yasminebassil/Desktop/everything/YA_Data/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA_Old'
names(non_nav_data)[15] <- 'NARA'
non_nav_data <- head(non_nav_data, n=26)
```

```{r organizing data, include=FALSE}
b1 <- subset(nav_data, Block_num == 1)
rownames(b1) <- NULL 
b2 <- subset(nav_data, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(nav_data, Block_num == 3)
rownames(b3) <- NULL 

mean_data <- subset(b3, select = c(Participant))

for (i in 1:nrow(b3)) {
  mean_data$Total_Time[i] <- (b3$Total_Time[i] + b2$Total_Time[i] + b1$Total_Time[i])/3
  mean_data$Orientation_Time[i] <- (b3$Orientation_Time[i] + b2$Orientation_Time[i] + b1$Orientation_Time[i])/3
  mean_data$Navigation_Time[i] <- (b3$Navigation_Time[i] + b2$Navigation_Time[i] + b1$Navigation_Time[i])/3
  mean_data$Distance[i] <- (b3$Distance[i] + b2$Distance[i] + b1$Distance[i])/3
  mean_data$Speed[i] <- (b3$Speed[i] + b2$Speed[i] + b1$Speed[i])/3
  mean_data$Mean_Dwell[i] <- (b3$Mean_Dwell[i] + b2$Mean_Dwell[i] + b1$Mean_Dwell[i])/3
  mean_data$Teleportations[i] <- (b3$Teleportations[i] + b2$Teleportations[i] + b1$Teleportations[i])/3
}

all_blocks <- aggregate(cbind(Total_Time, Orientation_Time, Navigation_Time, 
                              Distance, Speed, Mean_Dwell,
                              Teleportations) ~ Participant, 
                        data = nav_data, FUN = mean)

all_blocks$NARA <- non_nav_data$NARA
mean_data$NARA <- non_nav_data$NARA
```

## Correlations for Mean Outcome Measures vs NARA

```{r p_corr_ct}
p_corr_ct <- ggplot(mean_data, aes(x=NARA, y=Total_Time)) + 
  geom_point(data = mean_data, aes(color = Participant), size = 3, alpha = 0.5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Mean Total Time (s)")+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
  theme(legend.position = "none")
p_corr_ct
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig6_mean_ct.svg",
       height = 4, width=5, plot=p_corr_ct)
```


```{r echo=TRUE}
corr_ct <- cor.test(mean_data$Total_Time, mean_data$NARA, method = "spearman")
corr_ct
```


```{r p_corr_ct_nav}
p_corr_ctnav <- ggplot(mean_data, aes(x=NARA, y=Navigation_Time)) + 
  geom_point(data = mean_data, aes(color = Participant), size = 3, alpha = 0.5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Mean Navigation Time (s)")+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
  theme(legend.position = "none")
p_corr_ctnav
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig6_mean_ctnav.svg",
       height = 4, width=5, plot=p_corr_ctnav)
```

```{r echo=TRUE}
corr_ctnav <- cor.test(mean_data$Navigation_Time, mean_data$NARA, method = "spearman")
corr_ctnav
```

```{r p_corr_ct_ori}
p_corr_ctori <- ggplot(mean_data, aes(x=NARA, y=Orientation_Time)) + 
  geom_point(data = mean_data, aes(color = Participant), size = 3, alpha = 0.5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Mean Orientation Time (s)")+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
  theme(legend.position = "none")
p_corr_ctori
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig6_mean_ctori.svg",
       height = 4, width=5, plot=p_corr_ctori)
```

```{r echo=TRUE}
corr_ctori <- cor.test(mean_data$Orientation_Time, mean_data$NARA, method = "spearman")
corr_ctori
```

```{r p_corr_dt}
p_corr_dt <- ggplot(mean_data, aes(x=NARA, y=Distance)) + 
  geom_point(data = mean_data, aes(color = Participant), size = 3, alpha = 0.5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Mean Distance (VR m)")+
  theme(text = element_text(size = 18),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
  theme(legend.position = "none")
p_corr_dt
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig6_mean_dt.svg",
       height = 4, width=5, plot=p_corr_dt)
```

```{r echo=TRUE}
corr_dt <- cor.test(mean_data$Distance, mean_data$NARA, method = "spearman")
corr_dt
```

```{r p_corr_dwell}
p_corr_dwell <- ggplot(mean_data, aes(x=NARA, y=Mean_Dwell)) + 
  geom_point(data = mean_data, aes(color = Participant), size = 3, alpha = 0.5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Mean Dwell Time (s)")+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
  theme(legend.position = "none")
p_corr_dwell
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig6_mean_dwell.svg",
       height = 4, width=5, plot=p_corr_dwell)
```

```{r echo=TRUE}
corr_dwell <- cor.test(mean_data$Mean_Dwell, mean_data$NARA, method = "spearman")
corr_dwell
```

```{r p_corr_speed}
p_corr_speed <- ggplot(mean_data, aes(x=NARA, y=Speed)) + 
  geom_point(data = mean_data, aes(color = Participant), size = 3, alpha = 0.5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Mean Speed (VR m/s)")+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
  theme(legend.position = "none")
p_corr_speed
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig6_mean_speed.svg",
       height = 4, width=5, plot=p_corr_speed)
```

```{r echo=TRUE}
corr_speed <- cor.test(mean_data$Speed, mean_data$NARA, method = "spearman")
corr_speed
```

```{r p_corr_teleport}
p_corr_teleport <- ggplot(mean_data, aes(x=NARA, y=Teleportations)) + 
  geom_point(data = mean_data, aes(color = Participant), size = 3, alpha = 0.5)+
  scale_color_viridis(option = "plasma", discrete = TRUE)+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Mean Teleportations (count)")+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
  theme(legend.position = "none")
p_corr_teleport
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/fig6_mean_teleport.svg",
       height = 4, width=5, plot=p_corr_teleport)
```

```{r echo=TRUE}
corr_teleport <- cor.test(mean_data$Teleportations, mean_data$NARA, method = "spearman")
corr_teleport
```