---
title: "fig6_stats"
author: "Yasmine Bassil"
date: "2024-03-06"
output: html_document
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(corrplot)
```

```{r reading data, include=FALSE}
#This loads the data file as the variable "data"
nav_data <- read.csv('/Users/yasminebassil/Desktop/everything/YA_Data/averaged_results.csv')
# Tidying up the data
names(nav_data)[1] <- 'index'
names(nav_data)[2] <- 'Participant'
names(nav_data)[3] <- 'Block_num'
names(nav_data)[4] <- 'Total_Time'
names(nav_data)[5] <- 'Orientation_Time'
names(nav_data)[6] <- 'Navigation_Time'
names(nav_data)[7] <- 'Distance'
names(nav_data)[8] <- 'Speed'
names(nav_data)[9] <- 'Mean_Dwell'
names(nav_data)[10] <- 'Teleportations'
nav_data <- nav_data[ -c(1) ]
nav_data$Block_num <- as.factor(nav_data$Block_num)
sapply(nav_data, class)

#This loads the data file as the variable "data"
non_nav_data <- read.csv('/Users/yasminebassil/Desktop/everything/YA_Data/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA'
non_nav_data <- head(non_nav_data, n=26)
```

```{r organizing data, include=FALSE}
b1 <- subset(nav_data, Block_num == 1)
rownames(b1) <- NULL 
b2 <- subset(nav_data, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(nav_data, Block_num == 3)
rownames(b3) <- NULL 

change <- subset(b3, select = c(Participant))

for (i in 1:nrow(b3)) {
  change$Total_Time[i] <- b3$Total_Time[i] - b1$Total_Time[i]
  change$Orientation_Time[i] <- b3$Orientation_Time[i] - b1$Orientation_Time[i]
  change$Navigation_Time[i] <- b3$Navigation_Time[i] - b1$Navigation_Time[i]
  change$Distance[i] <- b3$Distance[i] - b1$Distance[i]
  change$Speed[i] <- b3$Speed[i] - b1$Speed[i]
  change$Mean_Dwell[i] <- b3$Mean_Dwell[i] - b1$Mean_Dwell[i]
  change$Teleportations[i] <- b3$Teleportations[i] - b1$Teleportations[i]
}

all_blocks <- aggregate(cbind(Total_Time, Orientation_Time, Navigation_Time, 
                              Distance, Speed, Mean_Dwell,
                              Teleportations) ~ Participant, 
                        data = nav_data, FUN = mean)

all_blocks$NARA <- non_nav_data$NARA
change$NARA <- non_nav_data$NARA
b1$NARA <- non_nav_data$NARA
change_paper <- change
```

```{r}
b1_b2 <- subset(b2, select = c(Participant))

for (i in 1:nrow(b3)) {
  b1_b2$Total_Time[i] <- b2$Total_Time[i] - b1$Total_Time[i]
  b1_b2$Orientation_Time[i] <- b2$Orientation_Time[i] - b1$Orientation_Time[i]
  b1_b2$Navigation_Time[i] <- b2$Navigation_Time[i] - b1$Navigation_Time[i]
  b1_b2$Distance[i] <- b2$Distance[i] - b1$Distance[i]
  b1_b2$Speed[i] <- b2$Speed[i] - b1$Speed[i]
  b1_b2$Mean_Dwell[i] <- b2$Mean_Dwell[i] - b1$Mean_Dwell[i]
  b1_b2$Teleportations[i] <- b2$Teleportations[i] - b1$Teleportations[i]
}
b1_b2$NARA <- non_nav_data$NARA

```


## Correlations between B1 All-Target Outcome Measures vs NARA

```{r p_corr_ct_b1}
p_corr_ct_b1 <- ggplot(b1, aes(x=NARA, y=Total_Time)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Time to Target (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ct_b1
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/b1_nara_corr_ct.svg",
       height = 4, width=5, plot=p_corr_ct_b1)
```

```{r echo=TRUE}
corr_b1_ct <- cor.test(b1$Total_Time, b1$NARA, method = "spearman")
corr_b1_ct
```

```{r p_corr_ctnav_b1}
p_corr_ctnav_b1 <- ggplot(b1, aes(x=NARA, y=Navigation_Time)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Navigation Time (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ctnav_b1
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/b1_nara_corr_ctnav.svg",
       height = 4, width=5, plot=p_corr_ctnav_b1)
```
```{r echo=TRUE}
corr_b1_ctnav <- cor.test(b1$Navigation_Time, b1$NARA, method = "spearman")
corr_b1_ctnav
```

```{r p_corr_ctori_b1}
p_corr_ctori_b1 <- ggplot(b1, aes(x=NARA, y=Orientation_Time)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Orientation Time (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ctori_b1
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/b1_nara_corr_ctori.svg",
       height = 4, width=5, plot=p_corr_ctori_b1)
```

```{r echo=TRUE}
corr_b1_ctori <- cor.test(b1$Orientation_Time, b1$NARA, method = "spearman")
corr_b1_ctori
```

```{r p_corr_dt_b1}
p_corr_dt_b1 <- ggplot(b1, aes(x=NARA, y=Distance)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Distance (VR m)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_dt_b1
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/b1_nara_corr_dt.svg",
       height = 4, width=5, plot=p_corr_dt_b1)
```

```{r echo=TRUE}
corr_b1_dt <- cor.test(b1$Distance, b1$NARA, method = "spearman")
corr_b1_dt
```

```{r p_corr_dwell_b1}
p_corr_dwell_b1 <- ggplot(b1, aes(x=NARA, y=Mean_Dwell)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Dwell Time (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_dwell_b1
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/b1_nara_corr_dwell.svg",
       height = 4, width=5, plot=p_corr_dwell_b1)
```

```{r echo=TRUE}
corr_b1_dwell <- cor.test(b1$Mean_Dwell, b1$NARA, method = "spearman")
corr_b1_dwell
```

```{r p_corr_speed_b1}
p_corr_speed_b1 <- ggplot(b1, aes(x=NARA, y=Speed)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Speed (VR m/s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_speed_b1
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/b1_nara_corr_speed.svg",
       height = 4, width=5, plot=p_corr_speed_b1)
```

```{r echo=TRUE}
corr_b1_speed <- cor.test(b1$Speed, b1$NARA, method = "spearman")
corr_b1_speed
```

```{r p_corr_teleport_b1}
p_corr_teleport_b1 <- ggplot(b1, aes(x=NARA, y=Teleportations)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Teleportations (count)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_teleport_b1
ggsave(file="/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/figure_creation/plots/b1_nara_corr_teleport.svg",
       height = 4, width=5, plot=p_corr_teleport_b1)
```

```{r echo=TRUE}
corr_b1_teleport <- cor.test(b1$Teleportations, b1$NARA, method = "spearman")
corr_b1_teleport
```

## Correlations between First Exposure Block (B2-B1) All-Target Outcome Measures vs NARA

```{r}
p_corr_ct_b1b2 <- ggplot(b1_b2, aes(x=NARA, y=Total_Time)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Time to Target (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ct_b1b2
```

```{r echo=TRUE}
corr_change_ct_b1b2 <- cor.test(b1_b2$Total_Time, b1_b2$NARA, method = "spearman")
corr_change_ct_b1b2
```

```{r}
p_corr_ctori_b1b2 <- ggplot(b1_b2, aes(x=NARA, y=Orientation_Time)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Orientation Time (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ctori_b1b2
```

```{r echo=TRUE}
corr_change_ctori_b1b2 <- cor.test(b1_b2$Orientation_Time, b1_b2$NARA, method = "spearman")
corr_change_ctori_b1b2
```

```{r}
p_corr_ctnav_b1b2 <- ggplot(b1_b2, aes(x=NARA, y=Navigation_Time)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Navigation Time (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ctnav_b1b2
```

```{r echo=TRUE}
corr_change_ctnav_b1b2 <- cor.test(b1_b2$Navigation_Time, b1_b2$NARA, method = "spearman")
corr_change_ctnav_b1b2
```

```{r}
p_corr_dt_b1b2 <- ggplot(b1_b2, aes(x=NARA, y=Distance)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Distance (VR m)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_dt_b1b2
```

```{r echo=TRUE}
corr_change_dt_b1b2 <- cor.test(b1_b2$Distance, b1_b2$NARA, method = "spearman")
corr_change_dt_b1b2
```

```{r}
p_corr_dwell_b1b2 <- ggplot(b1_b2, aes(x=NARA, y=Mean_Dwell)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Dwell Time (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_dwell_b1b2
```

```{r echo=TRUE}
corr_change_dwell_b1b2 <- cor.test(b1_b2$Mean_Dwell, b1_b2$NARA, method = "spearman")
corr_change_dwell_b1b2
```

```{r}
p_corr_speed_b1b2 <- ggplot(b1_b2, aes(x=NARA, y=Speed)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Speed (VR m/s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_speed_b1b2
```

```{r echo=TRUE}
corr_change_speed_b1b2 <- cor.test(b1_b2$Speed, b1_b2$NARA, method = "spearman")
corr_change_speed_b1b2
```

```{r}
p_corr_teleport_b1b2 <- ggplot(b1_b2, aes(x=NARA, y=Teleportations)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Teleportations (count)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_teleport_b1b2
```

```{r echo=TRUE}
corr_change_teleport_b1b2 <- cor.test(b1_b2$Teleportations, b1_b2$NARA, method = "spearman")
corr_change_teleport_b1b2
```

## Correlations between Block Change (B3-B1) All-Target Outcome Measures vs NARA

```{r p_corr_ct}
p_corr_ct <- ggplot(change, aes(x=NARA, y=Total_Time)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Time to Target (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ct
```

```{r echo=TRUE}
corr_change_ct <- cor.test(change$Total_Time, change$NARA, method = "spearman")
corr_change_ct
```

```{r p_corr_ctori}
p_corr_ctori <- ggplot(change, aes(x=NARA, y=Orientation_Time)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Orientation Time (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ctori
```

```{r echo=TRUE}
corr_change_ctori <- cor.test(change$Orientation_Time, change$NARA, method = "spearman")
corr_change_ctori
```
```{r p_corr_ctnav}
p_corr_ctnav <- ggplot(change, aes(x=NARA, y=Navigation_Time)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Navigation Time (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_ctnav
```

```{r echo=TRUE}
corr_change_ctnav <- cor.test(change$Navigation_Time, change$NARA, method = "spearman")
corr_change_ctnav
```

```{r p_corr_dt}
p_corr_dt <- ggplot(change, aes(x=NARA, y=Distance)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Distance (VR m)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_dt
```

```{r echo=TRUE}
corr_change_dt <- cor.test(change$Distance, change$NARA, method = "spearman")
corr_change_dt
```

```{r p_corr_dwell}
p_corr_dwell <- ggplot(change, aes(x=NARA, y=Mean_Dwell)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Dwell Time (s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_dwell
```

```{r echo=TRUE}
corr_change_dwell <- cor.test(change$Mean_Dwell, change$NARA, method = "spearman")
corr_change_dwell
```

```{r p_corr_speed}
p_corr_speed <- ggplot(change, aes(x=NARA, y=Speed)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Speed (VR m/s)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_speed
```

```{r echo=TRUE}
corr_change_speed <- cor.test(change$Speed, change$NARA, method = "spearman")
corr_change_speed
```

```{r p_corr_teleport}
p_corr_teleport <- ggplot(change, aes(x=NARA, y=Teleportations)) + 
  geom_point(color = "#ffa6b4")+
  geom_smooth(method=lm, color = "black", fill = "#ffa6b4")+
  ylab("Teleportations (count)")+
  xlim(0,100)+
  theme(text = element_text(size = 20),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
p_corr_teleport
```

```{r echo=TRUE}
corr_change_teleport <- cor.test(change$Teleportations, change$NARA, method = "spearman")
corr_change_teleport
```
```{r}

# List all dataframes in the global environment
dataframes <- ls()

# Filter dataframes that end with "anova"
dataframes_to_save <- dataframes[grep("^corr_change", dataframes)]

# Create an empty list to store dataframes
combined_dataframes <- list()

# Loop through the selected dataframes, combine them, and add a "Source" column
for (df_name in dataframes_to_save) {
  # Get the dataframe by name
  df <- get(df_name)
  
  # Add a "Source" column with the dataframe name
  df$Source <- df_name
  
  # Append the modified dataframe to the list
  combined_dataframes[[df_name]] <- df
}

# Combine all dataframes into one giant dataframe
final_combined_dataframe <- do.call(rbind, combined_dataframes)

# Specify the directory where you want to save the CSV file
output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/CogMap_Paper/stat_tests/"

# Define the CSV file name
csv_file <- paste0(output_directory, "b3b1_nara_corr_data.csv")

# Save the combined dataframe as a CSV file
write.csv(final_combined_dataframe, file = csv_file, row.names = FALSE)

# Print a message to confirm the save
cat("Saved combined data as", csv_file, "\n")

```